import { Ball } from './ball';
import { BallService } from './ball.service';

export const Balls: Ball[] = [
  { id: 1, name: 'Ball1', color: 'gray' },
  { id: 2, name: 'Ball2', color: 'gray' },
  { id: 3, name: 'Ball3', color: 'gray' },
  { id: 4, name: 'Ball4', color: 'gray' },
  { id: 5, name: 'Ball5', color: 'gray' },
  { id: 6, name: 'Ball6', color: 'gray' },
  { id: 7, name: 'Ball7', color: 'gray' },
  { id: 8, name: 'Ball8', color: 'gray' },
  { id: 9, name: 'Ball9', color: 'gray' },
  { id: 10, name: 'Ball10', color: 'gray' },
  { id: 11, name: 'Ball11', color: 'gray' },
  { id: 12, name: 'Ball12', color: 'gray' },
  { id: 13, name: 'Ball13', color: 'gray' },
  { id: 14, name: 'Ball14', color: 'gray' },
  { id: 15, name: 'Ball15', color: 'gray' },
  { id: 16, name: 'Ball16', color: 'gray' },
  { id: 17, name: 'Ball17', color: 'gray' },
  { id: 18, name: 'Ball18', color: 'gray' },
  { id: 19, name: 'Ball19', color: 'gray' },
  { id: 20, name: 'Ball20', color: 'gray' },
  { id: 20, name: 'Ball10', color: 'gray' },
  { id: 21, name: 'Ball21', color: 'gray' },
  { id: 22, name: 'Ball22', color: 'gray' },
  { id: 23, name: 'Ball23', color: 'gray' },
  { id: 24, name: 'Ball24', color: 'gray' },
  { id: 25, name: 'Ball25', color: 'gray' },
  { id: 26, name: 'Ball26', color: 'gray' },
  { id: 27, name: 'Ball27', color: 'gray' },
  { id: 28, name: 'Ball28', color: 'gray' },
  { id: 29, name: 'Ball29', color: 'gray' },
  { id: 30, name: 'Ball30', color: 'gray' },
];
